### ISSUE TITLE
Keep getting the same error

### ISSUE THREAD

**Issue by jordan-featherstone** [llazzaro/django-scheduler-sample#13]
```
from schedule.models.calendars import *
```

  File "C:\Python34\lib\site-packages\django_schedule-0.5b0-py3.4.egg\schedule\models\calendars.py", line 60
    raise Calendar.DoesNotExist, "Calendar does not exist."
                               ^
SyntaxError: invalid syntax

**Comment by llazzaro** [comment]
Are you using python 3? It seems that you are using a very old django-schedule version 0.5b.

please can you show the output of "pip freeze" to check which version are you using?

**Comment by jordan-featherstone** [comment]
I'm using Python 3.4.4,

**Comment by llazzaro** [comment]
yes I know you are using python 3, but you are using this project https://pypi.python.org/pypi/django-schedule/0.5b and not  "django-scheduler" https://pypi.python.org/pypi/django-scheduler.

django-scheduler (with the "r" at the end" ) is originally a fork of django-schedule. I added the "r" to keep maintaining the project (to add python 3 support, django 1.9).
Please let me know if you have issues with django-scheduler, but you are using other project and not this one.
