### ISSUE TITLE
NoArgsCommand removed in Django 1.10

### ISSUE THREAD

**Issue by andrew-computerscience** [llazzaro/django-scheduler-sample#14]
When one tries to load sample data for this sample project It appears the NoArgsCommand class has been removed from django.core.management.base in Django 1.10.

I reverted back to 1.9.6 and edited my requirements.txt file respectively and can now load sample data.

Hope this helps someone until the issue is rectified.

**Comment by llazzaro** [comment]
NoArgsCommand issue was solved on commit https://github.com/llazzaro/django-scheduler/commit/3e84346f18c166ac7cd94bca38bca351ceead6a9 however the version with that fix was not released to pypi.
you could try to install from github the develop branch of django-scheduler

**Comment by llazzaro** [comment]
Fixed. use latest version of scheduler please

**Comment by georgema1982** [comment]
I guess the requirements file needs to be updated as well.
