### ISSUE TITLE
TemplateDoesNotExist at / site_base.html

### ISSUE THREAD

**Issue by adamyala** [llazzaro/django-scheduler-sample#16]
I cloned the repo and followed setup instructions in the readme along with the instructions in https://github.com/llazzaro/django-scheduler-sample/issues/14

When I try to load the site I find that it's referencing a `site_base.html` that no longer exists.

**Comment by adamyala** [comment]
It looks like this change was introduced in commit 7472a10400baa5d1903265e8d38345fee82fa7e4

**Comment by PoDuck** [comment]
+1

Same issue

**Comment by PoDuck** [comment]
Well, I figured out a workaround, for now.  django-scheduler 1.8 doesn't play nice with django-1.10, so they upgraded it, but apparently this sample is not upgraded to handle django-scheduler 1.8.2.

Go through the install as normal.  Upgrade to 1.8.2, as it looks like you did (site_base.html errors happen with that version). Then load sample and example data, then revert back to dango-scheduler 1.8.0, and things play nicely again.
