### ISSUE TITLE
Two problems?

### ISSUE THREAD

**Issue by Palt0n** [llazzaro/django-scheduler-sample#18]
Hi, can't seem to get this sample working.

Problem 1:
django-scheduler-sample/project_sample/templates/homepage.html
Line 1: {% extends "site_base.html" %}
Instead of site_base.html change to base.html ?

Problem 2:
django-scheduler-sample/project_sample/urls.py
Line 13: url(r'^schedule/', include('schedule.urls')),
Refers to schedule which does not exist?

Sorry if I misunderstand, am very new to django.
Thanks

**Comment by llazzaro** [comment]
Thanks for reporting this.
the site_base problem was solved, just do a gill pull on master branch of the sample project.

For the other issue I found that this commit deleted the view: https://github.com/llazzaro/django-scheduler/commit/52f15f147bd0f000320851eaea19ce72053dac82#diff-c254b893db397b177aa55e3b4b6cdc9f

I will re add the view now on the development branch

**Comment by llazzaro** [comment]
Closing. Please install scheduler from the development brach if you want the fix now.

I will re upload sheduler to pypi this night.
To view the fix install scheduler with:

pip install git+https://github.com/llazzaro/django-scheduler.git
