### ISSUE TITLE
bower install

### ISSUE THREAD

**Issue by Palt0n** [llazzaro/django-scheduler-sample#19]
Hi,
Forgot to mention also, when doing
./manage.py bower install
it does:

Unable to find a suitable version for jquery, please choose one by typing one of the numbers below:
 1) jquery#~1.10.2 which resolved to 1.10.2 and is required by fullcalendar#1.6.4
 2) jquery#^3.1.1 which resolved to 3.1.1 and is required by django-scheduler-sample
 3) jquery#1.9.1 - 3 which resolved to 3.1.1 and is required by bootstrap#3.3.7
 4) jquery#^3.1.1 which resolved to 3.1.1

Thanks!

**Comment by llazzaro** [comment]
solved, please update your repo
