### ISSUE TITLE
Invalid field name(s) given in select_related:'occurrence

### ISSUE THREAD

**Issue by rugebiker** [llazzaro/django-scheduler-sample#2]
Hi,
I am trying to run this demo site (using django 1.8), and under "Available calendars" in example.com/schedule, all links from "tony_cal" and "Example Calendar" raise the following error:

```
FieldError at /schedule/calendar/year/tony/  <- (this changes related to the link clicked)

Invalid field name(s) given in select_related: 'occurrence'. Choices are: creator, rule, calendar
Error during template rendering
```

which gives an error in /foo/.venv/local/lib/python2.7/site-packages/schedule/templates/schedule/calendar_year.html line 9, which is:

```
{% for month in periods.year.get_months %}
```

any ideas on this?
thanks!

**Comment by llazzaro** [comment]
This was fixed on 0.7.5 version of django-scheduler.

Updated the requirements.txt
