### ISSUE TITLE
Wrong urls for full calendar static files

### ISSUE THREAD

**Issue by georgema1982** [llazzaro/django-scheduler-sample#20]
Right now the full calendar example is loading full calendar static files from /static/fullcalendar/fullcalendar.css and /static/fullcalendar/fullcalendar.js. It's giving an javascript error:

TypeError: $(...).fullCalendar is not a function

I think the right urls are /static/fullcalendar/dist/fullcalendar.css and /static/fullcalendar/dist/fullcalendar.css

**Comment by llazzaro** [comment]
are you using django-bower to install deps?

**Comment by georgema1982** [comment]
Yes

**Comment by AidanHanda** [comment]
ImportError: cannot import name 'NoArgsCommand'?

**Comment by oz123** [comment]
I can confirm this behavior. I cloned the repository, followed all the instructions in README and I am seeing that error.

@georgema1982, I managed to fix the issue. Checkout PR #22

**Comment by llazzaro** [comment]
thanks!
