### ISSUE TITLE
Empty Calendar not events are available on it

### ISSUE THREAD

**Issue by umarmughal824** [llazzaro/django-scheduler-sample#24]
Neither no events are being display nor any highlighted area with text is found on calendar.

Here is the image of the calendar which I have on my system after successfully running in my system. Beside that "python manage.py collectstatic" command also did not work.
[http://imgur.com/I1qdeeP](http://imgur.com/I1qdeeP)

This is what I get on change the date. 
 http://127.0.0.1:8000/schedule/api/occurrences?calendar_slug=example&start=2017-03-26&end=2017-05-07&_=1493202482852 404 (Not Found)
http://127.0.0.1:8000/schedule/api/occurrences?calendar_slug=example&start=2017-02-26&end=2017-04-09&_=1493202482853 404 (Not Found)

**Comment by cRyckreator** [comment]
@umarmughal824  
![image](https://cloud.githubusercontent.com/assets/9821393/25473262/58c21410-2b61-11e7-87ec-6136b9921603.png) 

./manage.py load_sample_data
./manage.py load_example_data

run these command to get sample data.
You may run into this error https://github.com/llazzaro/django-scheduler-sample/issues/21 and it tells you how to fix it.

**Comment by umarmughal824** [comment]
Yes I have already did that. Thanks for your help.

**Comment by llazzaro** [comment]
@cRyckreator  thanks for your answer. 
You can go to the admin to create new events also.
