### ISSUE TITLE
Color of the events not changing on calendar.

### ISSUE THREAD

**Issue by umarmughal824** [llazzaro/django-scheduler-sample#25]
I selected any color, but the calendar only shows default color (blue). How can I change the events colors? I did it in the event page but the color remains same.

**Comment by llazzaro** [comment]
@umarmughal824 thanks for reporting this. The issue will be solved on scheduler.

**Comment by llazzaro** [comment]
This was fixed on daily table.
On the year calendar it will be still shown as blue.
The fix works where the event is show, week and daily tables.

<img width="1048" alt="screen shot 2017-06-25 at 4 15 32 pm" src="https://user-images.githubusercontent.com/568181/27518964-89da3eae-59c1-11e7-8951-954877793cbf.png">

**Comment by llazzaro** [comment]
This will be released on version 0.8.5
