### ISSUE TITLE
NoReverseMatch at schedule/schedule

### ISSUE THREAD

**Issue by thejeffchen** [llazzaro/django-scheduler-sample#31]
I followed the steps above and got this problem here:

Error: Reverse for 'compact_calendar' not found. 'compact_calendar' is not a valid view function or pattern name.

It is pulling the error at "In template /usr/local/lib/python3.6/site-packages/schedule/templates/base.html, error at line 0" which doesn't make a lot of sense to me in the html template?

I checked the urls and it looks like 'compact_calendar' exists and the views make no reference to the 'compact_calendar' so I'm not sure what is happening?

**Comment by llazzaro** [comment]
All urls requires to add the namespace.
Latest version is still missing some fixes!

**Comment by goutomroy** [comment]
I have django==1.11.5 facing the same issue. when we can have the fix @llazzaro ? I was really waiting for the fix.

**Comment by llazzaro** [comment]
@goutomroy did the latest version fixed this issue?
