### ISSUE TITLE
ModuleNotFoundError: No module named 'schedule.urls'

### ISSUE THREAD

**Issue by Liamhanninen** [llazzaro/django-scheduler-sample#36]
In `project_sample/urls.py`:

`url(r'^schedule/', include('schedule.urls')),`

Caused:
`ModuleNotFoundError: No module named 'schedule.urls'`

I don't see the schedule app. Am I missing something?

**Comment by llazzaro** [comment]
You need to install the schedule dep, it should be installed with pip install -r requirements.txt.
Check here the project https://github.com/llazzaro/django-scheduler
