### ISSUE TITLE
Suggestion: update requirements.txt

### ISSUE THREAD

**Issue by BobBowles** [llazzaro/django-scheduler-sample#4]
I tried downloading/running this sample project to look at django-scheduler under python3.4, django 1.8.3.

I got errors from django-debug-toolbar, related to [this issue](https://github.com/django-debug-toolbar/django-debug-toolbar/issues/668). Upgrading to the latest version of django-debug-toolbar (1.3.2) fixed the problem. 

Assuming this does no harm to other deployment configurations, I suggest updating the django-debug-toolbar version in requirements.txt.

**Comment by llazzaro** [comment]
donde. thanks for reporting.
