### ISSUE TITLE
The standard install of django-scheduler does not seem to work for us.

### ISSUE THREAD

**Issue by pemccullough** [llazzaro/django-scheduler-sample#7]
The standard install of django-scheduler does not seem to work for us (windows 7, python 2.7). 

Therefore, we install django-scheduler as follows.
Create a file requirements.txt that contains this text: 
-e git+https://github.com/llazzaro/django-scheduler.git@master#egg=django-scheduler
django-debug-toolbar==1.3.2
Django==1.8

Then
pip install -r requirements.txt

For details see
https://github.com/llazzaro/django-scheduler-sample

**Comment by llazzaro** [comment]
can you paste a stack trace of the error?

**Comment by pemccullough** [comment]
Thanks for the note.
We had a number of issues and we had to back track.
We will not be using django-scheduler for now.
Sorry for the distraction.
Thanks for the contribution.
Paul

**Comment by llazzaro** [comment]
ok. I will close this issue.
In future we will not support python 2.7 anymore.
