### ISSUE TITLE
cannot find sample_project.settings

### ISSUE THREAD

**Issue by vanessadyce** [llazzaro/django-scheduler-sample#8]
I exported the settings but the project cannot find it and gives me the following error:

ImportError: No module named sample_project.settings

**Comment by clifftonc** [comment]
export DJANGO_SETTINGS_MODULE=sample_project.settings  is wrong 
it should be 
export DJANGO_SETTINGS_MODULE=project_sample.settings

**Comment by cliffton** [comment]
_export DJANGO_SETTINGS_MODULE=sample_project.settings_ is wrong 
it should be 
_export DJANGO_SETTINGS_MODULE=__project_sample__.settings_
